// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/Button.vue')['default']
    ButtonsCancel: typeof import('./src/components/buttons/Cancel.vue')['default']
    ButtonsCheck: typeof import('./src/components/buttons/Check.vue')['default']
    ButtonsClose: typeof import('./src/components/buttons/Close.vue')['default']
    ButtonsConfirm: typeof import('./src/components/buttons/Confirm.vue')['default']
    ButtonsExit: typeof import('./src/components/buttons/Exit.vue')['default']
    ButtonsPrint: typeof import('./src/components/buttons/Print.vue')['default']
    ButtonsSave: typeof import('./src/components/buttons/Save.vue')['default']
    ButtonsTryAgain: typeof import('./src/components/buttons/TryAgain.vue')['default']
    Modal: typeof import('./src/components/Modal.vue')['default']
    StatusConfirm: typeof import('./src/components/status/Confirm.vue')['default']
    StatusDeath: typeof import('./src/components/status/Death.vue')['default']
    StatusError: typeof import('./src/components/status/Error.vue')['default']
    StatusLoading: typeof import('./src/components/status/Loading.vue')['default']
    StatusSuccess: typeof import('./src/components/status/Success.vue')['default']
  }
}

export {}
