<template>
  <Button
    class="activity-button-finish"
    cursor-pointer
    text-white
    text-base
    md:text-lg
    font-bold
    bg-gray-500
    p-2
    md:p-4
    hover:opacity-70
  >
    <i
      class="activity-button-finish-icon"
      i-mdi-exit-to-app
      w-6
      h-6
    />
    <span class="activity-button-finish-text">
      Finalizar
    </span>
  </Button>
</template>
