<template>
  <Button
    class="activity-button-print"
    cursor-pointer
    text-white
    text-base
    md:text-lg
    font-bold
    bg-purple-500
    p-2
    md:p-4
    hover:opacity-70
  >
    <i
      class="activity-button-print-icon"
      i-mdi-printer
      w-6
      h-6
    />
    <span class="activity-button-print-text">
      Imprimir
    </span>
  </Button>
</template>
