/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./../components/Button.vue')['default']
    Confirmation: typeof import('./../components/Confirmation.vue')['default']
    Dead: typeof import('./../components/Dead.vue')['default']
    Footer: typeof import('./../components/Footer.vue')['default']
    Header: typeof import('./../components/Header.vue')['default']
    Loading: typeof import('./../components/Loading.vue')['default']
    Main: typeof import('./../components/Main.vue')['default']
    Marker: typeof import('./../components/Marker.vue')['default']
    Media: typeof import('./../components/Media.vue')['default']
    Message: typeof import('./../components/Message.vue')['default']
    Modal: typeof import('./../components/Modal.vue')['default']
    Resets: typeof import('./../components/Resets.vue')['default']
    Result: typeof import('./../components/Result.vue')['default']
    Section: typeof import('./../components/Section.vue')['default']
    Timer: typeof import('./../components/Timer.vue')['default']
  }
}
