/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Action: typeof import('./../components/Action.vue')['default']
    Button: typeof import('./../components/Button.vue')['default']
    Confirmation: typeof import('./../components/Confirmation.vue')['default']
    Dead: typeof import('./../components/Dead.vue')['default']
    Error: typeof import('./../components/Error.vue')['default']
    Footer: typeof import('./../components/Footer.vue')['default']
    Header: typeof import('./../components/Header.vue')['default']
    Lifes: typeof import('./../components/Lifes.vue')['default']
    Loading: typeof import('./../components/Loading.vue')['default']
    Main: typeof import('./../components/Main.vue')['default']
    Modal: typeof import('./../components/Modal.vue')['default']
    Result: typeof import('./../components/Result.vue')['default']
    Timer: typeof import('./../components/Timer.vue')['default']
  }
}
