// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Button: typeof import('./../components/Button.vue')['default']
    ButtonsCancel: typeof import('./../components/buttons/Cancel.vue')['default']
    ButtonsCheck: typeof import('./../components/buttons/Check.vue')['default']
    ButtonsClose: typeof import('./../components/buttons/Close.vue')['default']
    ButtonsConfirm: typeof import('./../components/buttons/Confirm.vue')['default']
    ButtonsFinish: typeof import('./../components/buttons/Finish.vue')['default']
    ButtonsPrint: typeof import('./../components/buttons/Print.vue')['default']
    ButtonsSave: typeof import('./../components/buttons/Save.vue')['default']
    ButtonsTryAgain: typeof import('./../components/buttons/TryAgain.vue')['default']
    Modal: typeof import('./../components/Modal.vue')['default']
    StatusConfirm: typeof import('./../components/status/Confirm.vue')['default']
    StatusDeath: typeof import('./../components/status/Death.vue')['default']
    StatusError: typeof import('./../components/status/Error.vue')['default']
    StatusLoading: typeof import('./../components/status/Loading.vue')['default']
    StatusSuccess: typeof import('./../components/status/Success.vue')['default']
  }
}
